server:
  port: 8080
spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/syss}
    username: ${SPRING_DATASOURCE_USERNAME:syss}
    password: ${SPRING_DATASOURCE_PASSWORD:syss}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost/issuer
minio:
  endpoint: ${MINIO_ENDPOINT:http://localhost:9000}
  accessKey: ${MINIO_ACCESS_KEY:syss}
  secretKey: ${MINIO_SECRET_KEY:sysssyss}
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true