server:
  port: 8080
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost/issuer
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true